### ISSUE TITLE
Avoid duplication of stack traces and binaries

### ISSUE THREAD

**Issue by xdevroey** [STAMP-project/ExRunner#1]
For now, ExRunner seems to store the binaries and stack traces in each tool directory. It creates a duplication for each tool. It would be better to save all the stack traces and binaries in a folder called `benchmark/` at the root level of ExRunner. 

This folder should have the same structure as the https://github.com/STAMP-project/JCrashPack repository (with `benchmark/applications`, `benchmark/crashes`). The idea is that one can clone the JCrashPack repository and readily use ExRunner with it.

**Comment by pderakhshanfar** [comment]
This enhancement is completed by commits 98fe8dd and 28c7244.
